modLoader="javafml"
loaderVersion="[0,)"
license="Not for sale"
[[mods]]
modId="endreborn"
logoFile="logo.png"
version="1.1.5"
displayName="Endorium"
credits = "All credits reserved"
authors="Me"
description="Type your text here"
[[dependencies.endreborn]]
  modId="minecraft"
  mandatory=true
  versionRange="${minecraft_version_range}"
  ordering="NONE"
  side="BOTH"
