modLoader="javafml"
loaderVersion="[0,)"
license="Not for sale"
[[mods]]
modId="endreborn"
logoFile="logo.png"
version="1.0.9"
displayName="Endorium"
credits = "All credits reserved"
authors="Me"
description="It's just a mod."
[[dependencies.endreborn]]
  modId="minecraft"
  mandatory=true
  versionRange="[1.20.1,1.21)"
  ordering="NONE"
  side="BOTH"
