modLoader="javafml"
loaderVersion="[2,)"
license="Not for sale"

[[mods]]
modId="endreborn"
logoFile="logo.png"
version="1.1.3"
displayName="Endorium"
credits = "All credits reserved"
authors="Me"
description="Type your text here"
[[dependencies.endreborn]]
modId="neoforge"
type="required"
versionRange="[21.0.40-beta,)"
ordering="NONE"
side="BOTH"
[[dependencies.endreborn]]
  modId="minecraft"
  mandatory=true
  versionRange="[1.21,1.22)"
  ordering="NONE"
  side="BOTH"